### ISSUE TITLE
Feature request: Add shorcut to "Team Inbox" in "Section navigation mode" (Todoist Business)

### ISSUE THREAD

**Issue by frankydee** [mgsloan/todoist-shortcuts#194]
Hi!

In Todoist Business, there is a "Team Inbox" just below the "Inbox" folder (only available to Business subscribers).   

After pressing <kbd>g</kbd> to enter "section navigation mode", there is no shorcut defined to select "Team Inbox":

![image](https://user-images.githubusercontent.com/32932612/149655865-c28005b3-cd0f-485d-b57e-9059f2ae53d5.png)

Would it be possible to define one please?  <kbd>t</kbd> would be perfect.

Thanks!  😊

P.S.:  @mgsloan, I bet this is news to you since I assume you're a Prod subscriber 😉

**Comment by mgsloan** [comment]
Sure!  What is the output of pasting the following into the developer console?

```
JSON.stringify(Array.from(document.querySelectorAll('#list_holder li')).slice(0,3).map(x => [x.id, x.attributes['data-track'].value]))
```

**Comment by mgsloan** [comment]
I've attempted to fix this in #194.  Should at least assign some keys to it, possibly `ti`, unless I guessed the matcher right in which case it will just be `t`

**Comment by frankydee** [comment]
Great! 👍 
Sorry for the dealy, here is the output:

`[["filter_inbox","navigation|inbox"],["filter_team_inbox","navigation|team_inbox"],["filter_today","navigation|today"]]`

BTW, <kbd>g</kbd> is now broken for me 😟  I get the following error in the dev console:

```
vendor.c734acd….js:130 Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at todoist-shortcuts.js:3485:25
    at addViaKeyFunc (todoist-shortcuts.js:3410:16)
    at assignKeysToItems (todoist-shortcuts.js:3483:5)
    at setupNavigate (todoist-shortcuts.js:3277:25)
    at todoist-shortcuts.js:1002:7
    at withId (todoist-shortcuts.js:4066:14)
    at navigate (todoist-shortcuts.js:988:5)
    at todoist-shortcuts.js:4732:34
    at _fireCallback (mousetrap.js:630:17)
    at Mousetrap.self._handleKey (mousetrap.js:699:21)
    at Mousetrap.handleKey (mousetrap.js:1052:32)
    at Mousetrap.self._handleKeyEvent (mousetrap.js:759:18)
    at Mousetrap.handleKeyEvent (mousetrap.js:926:19)
    at HTMLDocument.genericKeyHandler (todoist-shortcuts.js:4808:24)
    at HTMLDocument.i (vendor.c734acd….js:130:7154)
```

**Comment by mgsloan** [comment]
I've attempted to fix the error!  Does it work now?

**Comment by frankydee** [comment]
Sorry, still not working. This is what happens when I press <kbd>g</kbd>:

```
vendor.3cd6ff6fe7273ed3e38d.js?__WB_REVISION__=48d05bf7562c807b992c0c750378e66f:130 Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at assignKeysToItems (todoist-shortcuts.js:3569:28)
    at setupNavigate (todoist-shortcuts.js:3354:25)
    at todoist-shortcuts.js:1022:7
    at withId (todoist-shortcuts.js:4162:14)
    at navigate (todoist-shortcuts.js:1008:5)
    at todoist-shortcuts.js:4828:34
    at _fireCallback (mousetrap.js:630:17)
    at Mousetrap.self._handleKey (mousetrap.js:699:21)
    at Mousetrap.handleKey (mousetrap.js:1052:32)
    at Mousetrap.self._handleKeyEvent (mousetrap.js:759:18)
    at Mousetrap.handleKeyEvent (mousetrap.js:926:19)
    at HTMLDocument.genericKeyHandler (todoist-shortcuts.js:4904:24)
    at HTMLDocument.i (vendor.3cd6ff6fe7273ed3e38d.js?__WB_REVISION__=48d05bf7562c807b992c0c750378e66f:130:7154)

```

**Comment by mgsloan** [comment]
@frankydee Thanks for reporting! Should be fixed in version 142
